Coletor cnj: pré validador
dadosjusbr/parser-cnj pull request #12
Opened 2021-10-21 13:09 UTC by marcos-inja

## Pré validador
> Esse **PR** resolve a issue #10 

Adiciono um pré validador para confirmar se a planilhas tem mais que 10 linhas, caso tenha o coletor irá para o parser, caso não tenha exibirá a seguinte mensagem de erro:
**"Error! The number of lines, is less than the minimum number of 10 lines"**

Mudanças em outros arquivos:
- main: Agora passa a classe como parâmetro para acessar os dados das planilhas.
- parser: Não faz mais a leitura das planilhas lá, apenas acessa a classe Data.
- tests: Teste para o **validate**.

2021-10-21 13:19 UTC, marcos-inja commented on src/output_test/test_parser/expected.json
> +{
Acho que por conta das alterações que foram feitas no **protoDadosjusbr**, esse arquivo ficou maior.

2021-10-21 13:19 UTC, marcos-inja commented on src/parser_cnj.py
> -def read_data(path):
planilhas sendo lidas na classe **Data**

2021-10-21 13:19 UTC, marcos-inja commented on src/parser_cnj.py
> +    for row in fn:
mudo onde tem **fn** para outro nome?

2021-10-21 13:19 UTC, marcos-inja commented on src/parser_cnj.py
> +        update_employees(data.direitos_pessoais, employees, DIREITOS_PESSOAIS)
pega os dados da classe **Data**

2021-10-21 13:19 UTC, marcos-inja commented on src/parser_test.py
> +        result_data = parse(dados, 'tjrj/01/2018')
Alterado para rodar com a classe **Data**

2021-10-21 13:19 UTC, marcos-inja commented on src/data_test.py
> +        self.assertEqual(cm.exception.code, expected)
usei o sys.exit(), com uma mensagem, então aqui comparo as mensagens de saida

2021-10-21 13:19 UTC, marcos-inja commented on src/main.py
> +    dados.validate
Se não passar no validate, o script será encerrado

2021-10-21 18:54 UTC, danielfireman requested changes

2021-10-21 18:54 UTC, danielfireman commented on src/crawler.py
> -    time.sleep(5)
Por favor, remover este arquivo do PR. Não estamos mais nem utilizando crawler.py.

2021-10-21 18:54 UTC, danielfireman commented on src/data.py
> +    @property
Pelo que entendi, a utilização de `@property` não está correta: https://pt.stackoverflow.com/questions/364596/defini%C3%A7%C3%A3o-e-uso-do-property

Basta remover a linha 18.

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +class TestParser(unittest.TestCase):
```suggestion
class TestData(unittest.TestCase):
```

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +    def test_exit_number_lines(self):
```suggestion
    def test_validate(self):
```

2021-10-21 18:54 UTC, danielfireman commented on src/data.py
> +            )
`sys.exit` espera como parâmetro o código de retorno do processo.

```suggestion
            print(f"Os arquivos a serem consolidados tem menos que {MIN_ROWS} linhas e, por isso, são considerados inválidos.", file=sys.stderr)
            sys.exit(1)
```

2021-10-21 18:54 UTC, danielfireman commented on src/data.py
> +            )
`sys.exit` espera como parâmetro o código de retorno do processo.

```suggestion
            print(f"Erro lendo as planilhas: {excep}", file=sys.stderr)
            sys.exit(1)
```

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +        self.assertEqual(cm.exception.code, expected)
Bacana demais esse teste.

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +        self.assertEqual(cm.exception.code, expected)
```suggestion
        self.assertEqual(cm.exception.code, 1)
```

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +        expected = "Error! The number of lines, is less than the minimum number of 10 lines"
```suggestion
```

2021-10-21 18:54 UTC, danielfireman commented on src/data_test.py
> +        file_names = ['./output_test/test_data/TJPI-contracheque.xlsx',
tPode ser apenas `test_data`, não? Não precisamos de `output_test/test_data`

2021-10-21 18:54 UTC, danielfireman commented on src/main.py
> +if "DRIVER_PATH" in os.environ:
Ainda precisamos dessa variáveç de ambiente??

2021-10-21 18:54 UTC, danielfireman commented on src/main.py
> +    dados.validate
```suggestion
    dados.validate()
```

Validar é uma ação, Marcos. O mapeamento disso no mundo orientado a objetos é um método ou função e não uma propriedade (que é mapeado como campo ou dado a respeito da instância). Os parênteses deixam isso claro.

2021-10-22 10:56 UTC, marcos-inja commented on src/main.py
> +if "DRIVER_PATH" in os.environ:
Precisamos não, irei remover

2021-10-22 10:58 UTC, marcos-inja commented on src/data_test.py
> +        file_names = ['./output_test/test_data/TJPI-contracheque.xlsx',
Eu tô usando a pasta output, para guardar os arquivos do teste do parser, e do teste do validate, ai para ficar organizado coloquei essas pastas

2021-10-22 14:20 UTC, danielfireman approved these changes
Por favor endereçar meus comentários abaixo antes de fazer merge. Também deve realizar um teste para verificar se está tudo ok.

O código final ficou excelente!

2021-10-22 14:20 UTC, danielfireman commented on src/data.py
> +                self.direitos_pessoais = self.__read(file)
```suggestion
    def __read(file):
        try:
            data = pd.read_excel(file, engine='openpyxl').to_numpy()
        except Exception as excep:
            print(f"Erro lendo as planilhas: {excep}", file=sys.stderr)
            sys.exit(1)

        return data
        
def load(file_names)
    """Carrega os arquivos passados como parâmetros.
    
    :param file_names: slice contendo os arquivos baixados pelo coletor. Os nomes dos arquivos devem seguir uma convenção e começar com contracheque, indenizações, direitos-eventuais e direitos_pessoais.
    :return um objeto Data() pronto para operar com os arquivos
    """
    d = Data()
    for file in file_names:
        if 'contracheque' in file:
            data.contracheque = __read(file)
        if 'indenizações' in file:
            data.indenizacoes = __read(file)
        if 'direitos-eventuais' in file:
            data.direitos_eventuais = __read(file)
        if 'direitos-pessoais' in file:
            data.direitos_pessoais = __read(file)
    return data
 
class Data:
    def __init__(self, contracheque, indenizacoes, direitos_eventuais, direitos_pessoais):
        self.contracheque = contracheque
        self.indenizacoes = indenizacoes
        self.direitos_eventuais = direitos_eventuais
        self.direitos_pessoais = direitos_pessoais
```

2021-10-22 14:20 UTC, danielfireman commented on src/data_test.py
> +            dados = Data(file_names)
```suggestion
            dados = load(file_names)
```

2021-10-22 14:20 UTC, danielfireman commented on src/main.py
> +    dados = data.Data(file_names)
```suggestion
    dados = data.load(file_names)
```

2021-10-22 14:20 UTC, danielfireman commented on src/data.py
> +    def validate(self):
```suggestion
    def validate(self):
    """
    Validação inicial dos arquivos passados como parâmetros. Aborta a execução do script em caso de erro.
    """
```

2021-10-25 11:40 UTC, merged