Coletor CNJ: validador da planilha de controle de arquivos
dadosjusbr/parser-cnj pull request #13
Opened 2021-10-25 12:35 UTC by marcos-inja

## Controle de arquivos 
> **PR** relacionado a issue #11 

Adiciono um método para validar a existência de planilhas lendo a planilha de controle de arquivos, caso não exista dados correspondentes, o *script* será interrompido.

2021-10-25 12:41 UTC, marcos-inja commented on src/main.py
>      dados.validate() # Se não acontecer nada, é porque está tudo ok!
Adapto para chamar apenas um função? @danielfireman

2021-10-25 12:41 UTC, marcos-inja commented on src/parser_test.py
> +                 'output_test/test_parser/controle-de-arquivos-tjrj-2018-01.xlsx']
Acho que é melhor alterar o nome desse arquivos, e deixar eles com o padrão do coletor cnj cdp

2021-10-25 12:41 UTC, marcos-inja commented on src/data.py
> +def load(file_names, year, month):
Tô passando o ano e o mês para fazer a validação abaixo

2021-10-25 12:41 UTC, marcos-inja commented on src/data.py
> +                have_spreadsheet = True
Vejo se tem o mês e o ano, caso tenha passa de boa, caso não vai dar um erro

2021-10-25 13:29 UTC, danielfireman requested changes

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +def load(file_names, year, month):
Atualizar documentação abaixo

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
>      return data
```suggestion
    return Data(contracheque,
        indenizacoes,
        direitos_eventuais,
        direitos_pessoais,
        controle_de_arquivos,
        year,
        month)
    return data
```

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +    def validate_existence(self):
Não precisamos de outro método, pode colocar como parte do método `validate`

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +            sys.exit(1)
O status deve ser `4`

https://github.com/dadosjusbr/coletores/blob/master/status/status.go#L27

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +            sys.exit(1)
Por favor:
- criar uma constante para o 4
- Adicionar documentação explicando de onde vem o número e o que ele significa

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +                have_spreadsheet = True
adicionar um `break`?

2021-10-25 13:29 UTC, danielfireman commented on src/data.py
> +        have_spreadsheet = False
No caso de cima, precisamos dar um system exit com o código 5: `INVALID_INPUT`

https://github.com/dadosjusbr/coletores/blob/master/status/status.go#L30

2021-10-25 13:29 UTC, danielfireman commented on src/data_test.py
> +            dados.validate_existence()
Note que vai mudar quando a gente mudar tirar o novo método

2021-10-25 17:10 UTC, danielfireman requested changes

2021-10-25 17:10 UTC, danielfireman commented on src/data.py
> +        CODE_STATUS_ERROR_4 = 4
Os nomes podem designar o que as variáveis significam, Marcos. Adicionar semântica. Nesse caso, você está usando o nome da variável para dizer o valor, o que não é bom.

Nesse caso, 

https://github.com/dadosjusbr/coletores/blob/master/status/status.go#L27

`STATUS_DATA_UNAVAILABLE = 4`

https://github.com/dadosjusbr/coletores/blob/master/status/status.go#L30

`STATUS_INVALID_FILE = 5`

Também documentar (comentários) de onde vem esses números.

2021-10-25 17:10 UTC, danielfireman commented on src/data_test.py
> +        self.assertEqual(cm.exception.code, 4)
Usar as constantes ao invés dos números

2021-10-25 17:10 UTC, danielfireman commented on src/data.py
> +        sys.exit(1)
Aqui o status code tem que ser 5

https://github.com/dadosjusbr/coletores/blob/master/status/status.go#L30

`STATUS_INVALID_FILE`, abaixo.

2021-10-25 17:10 UTC, danielfireman commented on src/data.py
> +        CODE_STATUS_ERROR_4 = 4
Acho que pode mover para o pacote, ao invés de serem parte da classe.

2021-10-26 00:52 UTC, danielfireman requested changes
Ainda tem diversos comentários a serem endereçados. Poderia dar uma olhadinha, por favor?

2021-10-26 10:41 UTC, marcos-inja commented on src/data.py
> +        CODE_STATUS_ERROR_4 = 4
Realmente, estava a mesmo que deixar o numero direto haha

2021-10-26 10:41 UTC, marcos-inja commented on src/data.py
> +        sys.exit(1)
Mudei

2021-10-26 10:43 UTC, marcos-inja commented on src/data.py
> +        significa que as planilhas são invalidas.
Alterei a formatação para ficar melhor de ler!

2021-10-26 10:57 UTC, danielfireman approved these changes
Por favor, endereçar os comentários abaixo antes de fazer o merge.

2021-10-26 10:57 UTC, danielfireman commented on src/data.py
> +# Se for erro de não existir planilhas o retorno vai ser esse:
Coloque links para o código Go no staus, por favor. É importante essas coisas baterem

2021-10-26 10:57 UTC, danielfireman commented on src/parser_test.py
> +                 'output_test/test_parser/controle-de-arquivos-tjrj-2018-01.xlsx']
Concordo!

2021-10-26 10:57 UTC, danielfireman commented on src/parser_test.py
> +                 'output_test/test_parser/controle-de-arquivos-tjrj-2018-01.xlsx']
Não apenas estes, mas todos os acima

2021-10-26 11:27 UTC, marcos-inja commented on src/data.py
> +# Se for erro de não existir planilhas o retorno vai ser esse:
Não entendi

2021-10-26 11:58 UTC, merged