Parser CNJ: Remove restrição por linhas
dadosjusbr/parser-cnj pull request #17
Opened 2021-11-04 13:30 UTC by marcos-inja

## Remove restrição por numero de linhas linhas
> Esse **PR** resolve a issue #16 

Foi necessário alterar os seguintes arquivos:
|Arquivo|Mudança|
|-|-|
|`data.py`| Para remover a restrição pelo numero de linhas.|
|`parser_cnj.py`| Para aceitar os arquivos com o valor ***"0"** no lugar de um nome próprio.|
|`data_test.py`| Removido o teste de numero de linhas.|
|`parser_test.py`| Adicionado teste para planilhas com uma linha.|

@danielfireman, altero o nome desses arquivos de teste, para `test_parser.py` e `test_data.py`, para eles seguirem a convenção?

2021-11-04 13:36 UTC, marcos-inja commented on src/parser_cnj.py
> +        if not isNaN(name):
Vou deixar assim para não pegar linhas vazias.

2021-11-04 13:36 UTC, marcos-inja commented on src/parser_cnj.py
> +                membro.nome = str(name)
Converto para `string`, se não dar erro de tipo.

2021-11-04 13:36 UTC, marcos-inja commented on src/data.py
> +        HAVE_IN_SPREADSHEET = f'{self.month}/{self.year}'
De acordo com [o guia do mochileiro para python](https://docs.python-guide.org/), é bom fazer comparação com constantes haha

2021-11-04 14:21 UTC, danielfireman requested changes

2021-11-04 14:21 UTC, danielfireman commented on src/data.py
> +        HAVE_IN_SPREADSHEET = f'{self.month}/{self.year}'
Bacana que você está procurando fontes para melhorar a qualidade do código!

Só gostaria de pedir para mudar o nome, ele realmente não descrever o que a variável se destina. Nesse caso, penso que algo como `MONTH_YEAR_PATH` descreveria melhor

2021-11-04 14:21 UTC, danielfireman commented on src/data.py
> +            if HAVE_IN_SPREADSHEET in row:
Pode colocar um break para sair do for depois que `have_spreadsheet` fosse igual a True?

2021-11-04 14:21 UTC, danielfireman commented on src/parser_cnj.py
> +        if not isNaN(name):
Ok

2021-11-04 14:21 UTC, danielfireman commented on src/parser_cnj.py
> +        if not isNaN(name):
Pode colocar um comentário no código, por favor?

2021-11-04 14:21 UTC, danielfireman commented on src/parser_cnj.py
> +                membro.nome = str(name)
Pode colocar um colar um comentário no código, por favor?

2021-11-05 10:41 UTC, marcos-inja commented on src/data.py
> +            if HAVE_IN_SPREADSHEET in row:
Feito!

2021-11-05 13:15 UTC, danielfireman approved these changes

2021-11-05 13:16 UTC, merged