Adição da mensagem para Metadado
dadosjusbr/parser-cnj pull request #7
Opened 2021-10-05 18:49 UTC by joaolgm

2021-10-05 20:29 UTC, danielfireman requested changes

2021-10-05 20:29 UTC, danielfireman commented on src/metadado.py
> +        metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
A quantidade de linhas não define o nível de detalhamento. Você precisa olhar a planilha e verificar as colunas. Isso deve ser constante.

2021-10-05 20:29 UTC, danielfireman commented on src/metadado.py
> +    resultado_coleta.metadados.CopyFrom(metadado)
Retorna o metadado, por favor.

2021-10-05 20:29 UTC, danielfireman commented on src/metadado.py
> +    for remuneracao in resultado_coleta.folha.contra_cheque[0].remuneracoes.remuneracao:
Provavelmente você não vai precisar do resultado_coleta

2021-10-05 20:29 UTC, danielfireman commented on src/metadado.py
> +    metadado.estritamente_tabular = True
Tem certeza que o formato é estritamente tabular, por favor conferir.

2021-10-05 20:29 UTC, danielfireman commented on src/main.py
> +    metadado.captura(rc)
```suggestion
    m = metadado.Novo()
    resultado_coleta.metadados.CopyFrom(m)
```

2021-10-06 12:47 UTC, joaolgm commented on src/metadado.py
> +        metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Eu to pegando o primeiro funcionário e verificando quantas colunas de receita e despesa que ele possui, separando também se é BASE ou OUTRAS. Não funciona igual?

2021-10-06 12:49 UTC, danielfireman commented on src/metadado.py
> +        metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Seu objetivo é se proteger para o caso do CNJ mudar o formato dos dados e a gente não perceber? 

Falando pois minha proposta é mais simples. Nesse momento, optaria pela simplicidade.

2021-10-06 14:11 UTC, joaolgm commented on src/metadado.py
> +        metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Isso, caso algo mude somente o parser terá que se adaptar, além de que não preciso abrir novamente a planilha e aproveito a classificação feita pela mensagem FolhaDePagamento do protobuf(que classifica receita e despesa). Mas também posso verificar as colunas direto na planilha, prefere assim?

2021-10-06 14:14 UTC, joaolgm commented on src/metadado.py
> +    metadado.estritamente_tabular = True
toda linha é uma variável e toda coluna um valor, certo?
![image](https://user-images.githubusercontent.com/20714862/136220264-e5fe44d2-116d-469f-b2f7-c4ea18f04a6b.png)

2021-10-06 17:04 UTC, danielfireman commented on src/metadado.py
> +    metadado.estritamente_tabular = True
Isso. Está certo.

2021-10-06 17:08 UTC, danielfireman commented on src/metadado.py
> +        metadado.outras_receitas = Coleta.Metadados.OpcoesDetalhamento.DETALHADO
Refleti um pouco e acho que podemos tomar a decisão baseado nas planilhas sim. Não estou bem certo do algoritmo de decisão (por isso sugiro que seja manual agora). Além disso, também simplificará bastante o código. Se for o caso, depois revisitamos.

2021-10-07 14:24 UTC, danielfireman approved these changes

2021-10-07 14:28 UTC, merged